/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/PizzaBox.glb
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations, useTexture, Decal } from "@react-three/drei";
import { useSnapshot } from "valtio";
import state from "../../../store";
import * as THREE from "three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/PizzaBox.glb");
  const { actions } = useAnimations(animations, group);
  const [hovered, sethover] = useState(null);
  const snap = useSnapshot(state);

  const logotexture = useTexture(snap.logoDecal);
  const fulltexture = useTexture(snap.fullDecal);

  const textureLoader = new THREE.TextureLoader();
  const imageTexture = textureLoader.load("path_to_your_image.png"); // Replace with the path to your image

  //console.log(hovered, state.current)
  //console.log(snap.items.CardBoardExterior)
  console.log("ext", logotexture);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={(e) => {
        e.stopPropagation();
        sethover(e.object.material.name);
      }}
      onPointerOut={(e) => {
        e.intersections.length === 0 && sethover(null);
        sethover(e.object.material.name);
      }}
      onPointerDown={(e) => {
        e.stopPropagation();
        state.current = e.object.material.name;
      }}
      onPointerMissed={(e) => {
        state.current = null;
      }}
    >
      <group name="Scene">
        <group
          name="Armature"
          position={[-0.168, 0, 0]}
          rotation={[0, 0, 0.489]}
          scale={0.016}
        >
          <primitive object={nodes.Base} />
          <group name="Box_12in">
            <skinnedMesh
              material-color={snap.items.CardboardInterior}
              name="Plane002"
              geometry={nodes.Plane002.geometry}
              material={materials.CardboardInterior}
              skeleton={nodes.Plane002.skeleton}
            >
              {snap.isLogoTexture && state.items.CardboardInterior && (
                <primitive object={imageTexture} attach="map" />
              )}
            </skinnedMesh>

            <skinnedMesh
              material-color={snap.items.CardBoardExterior}
              name="Plane002_1"
              geometry={nodes.Plane002_1.geometry}
              material={materials.CardBoardExterior}
              skeleton={nodes.Plane002_1.skeleton}
            ></skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/PizzaBox.glb");
