/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/box.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Box = (props) => {
  const { nodes, materials } = useGLTF("/box.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
      <mesh
        geometry={nodes.imagetostl_mesh1.geometry}
        material={materials.mat1}
      />
    </group>
  );
};

useGLTF.preload("/box.glb");

export default Box;
